// <auto-generated />
using System;
using Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ProyectoDbContext))]
    partial class ProyectoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacion.Dominio.Proyecto", b =>
                {
                    b.Property<Guid>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("IdProject");

                    b.ToTable("Proyecto");

                    b.HasData(
                        new
                        {
                            IdProject = new Guid("15c33d17-0fd2-42cb-a38e-9016a802fbdd"),
                            Nombre = "Proyecto_1"
                        },
                        new
                        {
                            IdProject = new Guid("e263ca67-7790-40bb-b5a1-e75cb125f85f"),
                            Nombre = "Proyecto_2"
                        },
                        new
                        {
                            IdProject = new Guid("e2618a6c-ff07-46b6-99a7-d1dfeb05428a"),
                            Nombre = "Proyecto_3"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("IdUsuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("ProyectoIdProject")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ProyectoIdProject");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5e3bc1a-5cec-4710-a238-12e6ac029d98"),
                            Descripcion = "",
                            Estado = "Abierto",
                            Nombre = "Programacion"
                        },
                        new
                        {
                            Id = new Guid("deaac420-03df-4dec-a1c1-9c68640a8319"),
                            Descripcion = "",
                            Estado = "Abierto",
                            Nombre = "Analisis"
                        },
                        new
                        {
                            Id = new Guid("4b91ce3e-d1b7-4537-82c9-fdabef627ca5"),
                            Descripcion = "",
                            Estado = "Abierto",
                            Nombre = "Logica"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("ProyectoIdProject")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoIdProject");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9cb398d-3924-42a0-baf0-787cd58f69b0"),
                            Nombre = "User_1"
                        },
                        new
                        {
                            Id = new Guid("1d98bb2f-d25b-4b4b-a5ab-8f87eaf6cc3b"),
                            Nombre = "User_2"
                        },
                        new
                        {
                            Id = new Guid("52175b47-342e-4047-8c72-463386cf1908"),
                            Nombre = "User_3"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Ticket", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Usuario", "UsuarioTicket")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.HasOne("Aplicacion.Dominio.Proyecto", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ProyectoIdProject");

                    b.Navigation("UsuarioTicket");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Usuario", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Proyecto", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("ProyectoIdProject");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Proyecto", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
